//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use std::borrow::Cow;

use sea_orm::entity::prelude::*;

use crate::table::ToTableRecord;

type Entity = CollectionMediaEntity;
type Model = CollectionMediaModel;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct CollectionMediaEntity;

impl EntityName for CollectionMediaEntity {
    fn table_name(&self) -> &str {
        "collection_media"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq)]
pub struct CollectionMediaModel {
    pub media_id: i64,
    pub collection_id: i64,
}

impl ToTableRecord<2> for CollectionMediaModel {
    fn to_record(&self) -> [Cow<'_, str>; 2] {
        [
            Cow::Owned(self.media_id.to_string()),
            Cow::Owned(self.collection_id.to_string()),
        ]
    }
}

impl ToTableRecord<2> for &CollectionMediaModel {
    fn to_record(&self) -> [Cow<'_, str>; 2] {
        [
            Cow::Owned(self.media_id.to_string()),
            Cow::Owned(self.collection_id.to_string()),
        ]
    }
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    MediaId,
    CollectionId,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    MediaId,
    CollectionId,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = (i64, i64);
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Media,
    Set,
}

impl ColumnTrait for Column {
    type EntityName = CollectionMediaEntity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::MediaId => ColumnType::BigInteger.def(),
            Self::CollectionId => ColumnType::BigInteger.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Media => CollectionMediaEntity::belongs_to(super::media::Entity)
                .from(Column::MediaId)
                .to(super::media::Column::Aid)
                .into(),
            Self::Set => CollectionMediaEntity::belongs_to(super::collection::CollectionEntity)
                .from(Column::CollectionId)
                .to(super::collection::Column::CollectionId)
                .into(),
        }
    }
}

impl Related<super::media::MediaEntity> for CollectionMediaEntity {
    fn to() -> RelationDef {
        Relation::Media.def()
    }
}

impl Related<super::collection::CollectionEntity> for CollectionMediaEntity {
    fn to() -> RelationDef {
        Relation::Set.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
