//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

type Entity = StatusEntity;
type Model = StatusModel;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct StatusEntity;

impl EntityName for StatusEntity {
    fn table_name(&self) -> &str {
        "status"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq)]
pub struct StatusModel {
    #[sea_orm(primary_key, auto_increment = true)]
    pub id: Option<i64>,
    pub name: String,
    pub path: String,
    pub state: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    Name,
    Path,
    State,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i64;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    MediaSet,
}

impl ColumnTrait for Column {
    type EntityName = StatusEntity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::TinyInteger.def(),
            Self::Name => ColumnType::String(StringLen::None).def(),
            Self::Path => ColumnType::String(StringLen::None).def(),
            Self::State => ColumnType::custom("enum_text").def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::MediaSet => StatusEntity::has_many(super::collection::CollectionEntity).into(),
        }
    }
}

impl Related<super::collection::CollectionEntity> for StatusEntity {
    fn to() -> RelationDef {
        super::collection_media::Relation::Set.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::collection_media::Relation::Media.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
