//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

use crate::{entity::UpperCid, table::ToTableRecord};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "up"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq)]
pub struct Model {
    pub up_id: UpperCid,
    pub name: String,
    pub state: String,
}

impl ToTableRecord<3> for Model {
    fn to_record(self) -> [String; 3] {
        [self.up_id.to_string(), self.name, self.state]
    }
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    UpId,
    Name,
    State,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    UpId,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i64;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    MediaUp,
    UpAccount,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::UpId => ColumnType::BigInteger.def(),
            Self::Name => ColumnType::String(StringLen::None).def(),
            Self::State => ColumnType::custom("enum_text").def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::MediaUp => Entity::has_many(super::up_media::UpMediaEntity).into(),
            Self::UpAccount => Entity::has_many(super::up_account::Entity).into(),
        }
    }
}

impl Related<super::up_media::UpMediaEntity> for Entity {
    fn to() -> RelationDef {
        Relation::MediaUp.def()
    }
}

impl Related<super::up_account::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UpAccount.def()
    }
}

impl Related<super::account::AccountEntity> for Entity {
    fn to() -> RelationDef {
        super::up_account::Relation::Account.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::up_account::Relation::Up.def().rev())
    }
}

impl Related<super::media::MediaEntity> for Entity {
    fn to() -> RelationDef {
        super::up_media::Relation::Media.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::up_media::Relation::Up.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
