//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use std::borrow::Cow;

use sea_orm::entity::prelude::*;

use crate::table::ToTableRecord;

pub type UpperMediaModel = Model;
pub type UpperMediaEntity = Entity;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Hash)]
#[sea_orm(table_name = "upper_media")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub media_id: i64,
    #[sea_orm(primary_key, auto_increment = false)]
    pub upper_id: i64,
}

impl ToTableRecord<2> for Model {
    fn to_record(&self) -> [Cow<'_, str>; 2] {
        [
            Cow::Owned(self.media_id.to_string()),
            Cow::Owned(self.upper_id.to_string()),
        ]
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Media,
    Upper,
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Media => UpperMediaEntity::belongs_to(super::media::Entity)
                .from(Column::MediaId)
                .to(super::media::Column::Aid)
                .into(),
            Self::Upper => UpperMediaEntity::belongs_to(super::upper::Entity)
                .from(Column::UpperId)
                .to(super::upper::Column::UpperId)
                .into(),
        }
    }
}

impl Related<super::media::MediaEntity> for UpperMediaEntity {
    fn to() -> RelationDef {
        Relation::Media.def()
    }
}

impl Related<super::upper::Entity> for UpperMediaEntity {
    fn to() -> RelationDef {
        Relation::Upper.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
