//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use std::borrow::Cow;

use sea_orm::entity::prelude::*;

use crate::table::ToTableRecord;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "upper_account"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq)]
pub struct Model {
    pub upper_id: i64,
    pub account_id: i64,
}

impl ToTableRecord<2> for Model {
    fn to_record(&self) -> [Cow<'_, str>; 2] {
        [
            Cow::Owned(self.upper_id.to_string()),
            Cow::Owned(self.account_id.to_string()),
        ]
    }
}

impl ToTableRecord<2> for &Model {
    fn to_record(&self) -> [Cow<'_, str>; 2] {
        [
            Cow::Owned(self.upper_id.to_string()),
            Cow::Owned(self.account_id.to_string()),
        ]
    }
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    UpperId,
    AccountId,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    UpperId,
    AccountId,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = (i64, i64);
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Account,
    Up,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::UpperId => ColumnType::BigInteger.def(),
            Self::AccountId => ColumnType::BigInteger.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Account => Entity::belongs_to(super::account::AccountEntity)
                .from(Column::AccountId)
                .to(super::account::Column::AccountId)
                .into(),
            Self::Up => Entity::belongs_to(super::upper::Entity)
                .from(Column::UpperId)
                .to(super::upper::Column::UpperId)
                .into(),
        }
    }
}

impl Related<super::account::AccountEntity> for Entity {
    fn to() -> RelationDef {
        Relation::Account.def()
    }
}

impl Related<super::upper::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Up.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
