//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

type Entity = AccountCollectionEntity;
type Model = AccountCollectionModel;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct AccountCollectionEntity;

impl EntityName for AccountCollectionEntity {
    fn table_name(&self) -> &str {
        "set_account"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq)]
pub struct AccountCollectionModel {
    pub set_id: i64,
    pub account_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    SetId,
    AccountId,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    SetId,
    AccountId,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = (i64, i64);
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Account,
    Set,
}

impl ColumnTrait for Column {
    type EntityName = AccountCollectionEntity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::SetId => ColumnType::BigInteger.def(),
            Self::AccountId => ColumnType::BigInteger.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Account => AccountCollectionEntity::belongs_to(super::account::AccountEntity)
                .from(Column::AccountId)
                .to(super::account::Column::AccountId)
                .into(),
            Self::Set => AccountCollectionEntity::belongs_to(super::collection::CollectionEntity)
                .from(Column::SetId)
                .to(super::collection::Column::SetId)
                .into(),
        }
    }
}

impl Related<super::account::AccountEntity> for AccountCollectionEntity {
    fn to() -> RelationDef {
        Relation::Account.def()
    }
}

impl Related<super::collection::CollectionEntity> for AccountCollectionEntity {
    fn to() -> RelationDef {
        Relation::Set.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
