//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

type Entity = CollectionMediaEntity;
type Model = CollectionMediaModel;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct CollectionMediaEntity;

impl EntityName for CollectionMediaEntity {
    fn table_name(&self) -> &str {
        "media_set"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq)]
pub struct CollectionMediaModel {
    pub id: i64,
    pub set_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    SetId,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
    SetId,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = (i64, i64);
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Media,
    Set,
}

impl ColumnTrait for Column {
    type EntityName = CollectionMediaEntity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::BigInteger.def(),
            Self::SetId => ColumnType::BigInteger.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Media => CollectionMediaEntity::belongs_to(super::media::MediaEntity)
                .from(Column::Id)
                .to(super::media::Column::Aid)
                .into(),
            Self::Set => CollectionMediaEntity::belongs_to(super::collection::CollectionEntity)
                .from(Column::SetId)
                .to(super::collection::Column::SetId)
                .into(),
        }
    }
}

impl Related<super::media::MediaEntity> for CollectionMediaEntity {
    fn to() -> RelationDef {
        Relation::Media.def()
    }
}

impl Related<super::collection::CollectionEntity> for CollectionMediaEntity {
    fn to() -> RelationDef {
        Relation::Set.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
