//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

type Entity = CollectionEntity;
type Model = CollectionModel;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct CollectionEntity;

impl EntityName for CollectionEntity {
    fn table_name(&self) -> &str {
        "set"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq)]
pub struct CollectionModel {
    pub set_id: i64,
    pub name: String,
    pub count: i64,
    pub state: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    SetId,
    Name,
    Count,
    State,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    SetId,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i64;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    MediaSet,
    SetAccount,
}

impl ColumnTrait for Column {
    type EntityName = CollectionEntity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::SetId => ColumnType::BigInteger.def(),
            Self::Name => ColumnType::String(StringLen::None).def(),
            Self::Count => ColumnType::BigInteger.def(),
            Self::State => ColumnType::custom("enum_text").def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::MediaSet => CollectionEntity::has_many(super::collection_media::CollectionMediaEntity).into(),
            Self::SetAccount => CollectionEntity::has_many(super::account_collection::AccountCollectionEntity).into(),
        }
    }
}

impl Related<super::collection_media::CollectionMediaEntity> for CollectionEntity {
    fn to() -> RelationDef {
        Relation::MediaSet.def()
    }
}

impl Related<super::account_collection::AccountCollectionEntity> for CollectionEntity {
    fn to() -> RelationDef {
        Relation::SetAccount.def()
    }
}

impl Related<super::account::AccountEntity> for CollectionEntity {
    fn to() -> RelationDef {
        super::account_collection::Relation::Account.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::account_collection::Relation::Set.def().rev())
    }
}

impl Related<super::media::MediaEntity> for CollectionEntity {
    fn to() -> RelationDef {
        super::collection_media::Relation::Media.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::collection_media::Relation::Set.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
